#!groovy

pipeline {

    agent {
        docker {
            label 'docker-agent'
            image 'node:6'
            args '-v $HOME:/app'
        }
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }


    stages {
        stage('Build') {
            steps {
                sh "hostname"
                echo "Hello from docker-container ${params.PERSON}"
            }
        }
    }

}