#!groovy

pipeline {

    agent {
        docker {
            image 'node:6'
            args '-v $HOME:/app'
        }
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }


    stages {
        stage('Build') {
            steps {
                echo "done ${params.env}"
            }
        }
    }

}