#!groovy
currentBuild.description = "${params.env == 'production' ? '🎩' : '🧢'} env=${params.env}"

pipeline {

    agent any
    parameters {
        choice(
                name: 'env',
                choices: "staging\nproduction",
                description: 'Deploy to environment'
        )
    }
    environment {
        ENV_NAME = "${params.env}"
        MAIN_WORKSPACE="${WORKSPACE}"
    }
    stages {
        stage('Build') {
            steps {
                echo "done ${params.env} ${MAIN_WORKSPACE} ${ENV_NAME}"
            }
        }
        stage('Deploy') {
            when {
                not {
                    anyOf {
                        branch 'master'
                        branch 'release/*'
                        changeset 'src/**/*'
                    }
                }
            }
            agent {
                label: 'deployer'
            }
            steps {
                echo "deploying ${params.env} ${MAIN_WORKSPACE} ${ENV_NAME}"
            }
        }
    }

}