#!groovy
currentBuild.description = "🎩🧢"
pipeline {

    agent any
    stages {
        stage("test") {
//          cannot have agent here for parallel + can only have steps or parallel
//            agent { label 'java' }
            parallel {
                stage("test-front-end") {
                    // cannot have parallel within parallel
//                    agent { label 'node' }
                    steps {
                        echo "TESTING front-end"
                    }
                }
                stage("test-back-end") {
//                    agent { label 'java' }
                    steps {
                        echo "TESTING back-end"
                    }
                }
            }
        }
    }

}