#!groovy

pipeline {

    agent any

    stages {
        stage('build') {
            steps {
                sh 'echo step1'
                sh 'echo step2'
                sh '''
                echo 'Multiline'
                echo 'Example'
             '''
                echo 'not using shell'
            }
        }
        stage('test') {
            steps {
                sh 'fail me please'
            }

            post {
                always {
                    echo 'This will always run in test'
                }
                failure {
                    echo 'This will run only if failed'
                }
                changed {
                    echo 'This will run only if the state of the Pipeline has changed'
                }
            }
        }
    }

    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, the Pipeline was previously failing but is now successful'
        }
    }

}