#!groovy

pipeline {

    agent any

    stages {
        //.. build test
        stage ('check') {
            steps {
                timeout(time: 40, unit: 'MINUTES') {
                    input message: 'Deploy to production?', ok: 'YES'
                    script {
                        echo 'deploy'
                    }
                }
            }
        }

    }

}