#!groovy

pipeline {

    agent any

    stages {
        //.. build test
        timeout(time: 40, unit: 'MINUTES') {
            input message: 'Deploy to production?', ok: 'YES'
            node {
                echo 'deploy'
            }
        }


    }

}