#!groovy

pipeline {

    agent {
        docker {
            image 'alpine'
            label 'docker-agent'
            args  '-v /tmp:/tmp'
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'echo from docker'
                sh 'echo step2'
                sh '''
                echo 'Multiline'
                echo 'Example'
             '''
                echo 'not using shell2'
            }
        }
    }



}