#!groovy


//Can be used like this OR in script of steps
//node {
//    jobDefinitions = load './definitions.job'
//    dir('./pipelines')
//    {
//        git url: 'https://github.com/hasnat/stateless-jenkins.git'
//    }
//    externalJobDefinition = load './pipelines/commons/common.groovy'
//}

pipeline {

    agent any
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }


    stages {
        stage('Build') {
            steps {
                script {
                    jobDefinitions = load './definitions.job'
                    dir('pipelines')
                    {
                        git url: 'https://github.com/hasnat/stateless-jenkins.git'
                    }

                    externalJobDefinition = load 'pipelines/commons/common.groovy'
                }
                script {
                    jobDefinitions.hello_local(params.PERSON)
                    externalJobDefinition.hello(params.PERSON)
                    hello_same_file('hi')

                }
            }
        }
    }

}


def hello_same_file(whom) {
    echo "Hello ${whom} (from hello_same_file)"
}